preprocess:
  input_dir: data/petImages
  output_dir: data/processed
  image_size: 224
  max_images: 2000

train:
  batch_size: 64
  epochs: 10
  learning_rate: 0.002
  image_size: 224
  validation_split: 0.2
